version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-orcafin
    hostname: sqlserver-orcafin
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "!Admin123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - orcafin-net

volumes:
  sql_data:

networks:
  orcafin-net:
    driver: bridge
