version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=orcafin_db
      - POSTGRES_USER=orcafin_user
      - POSTGRES_PASSWORD=orcafin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: